### ISSUE TITLE
Volume breaking: make volumes divisible by 4 and pad the end with empty pages

### ISSUE THREAD

**Issue by jukkae** [snaekobbi/pipeline-mod-celia#26]
- [x] The number of pages in each volume should be divisible by 4 to avoid empty pages in the middle of the volume.
- [x] There should be at least one empty sheet at the end of the book to protect the braille print.

**Comment by jukkae** [comment]
Initial idea for implementation: process the pef in mod-celia `dtbook-to-pef.xpl` after `<px:dtbook-to-pef.convert>`

**Comment by bertfrees** [comment]
Your initial idea sounds to way to go.

**Comment by jukkae** [comment]
Good. Note-to-self: care must be taken with `max-length`, because the volume must still be shorter than or equal to `max-length`, even with the added empty padding sheets.
