### ISSUE TITLE
Constrain volume length to $maximum-number-of-sheets even when post-processing

### ISSUE THREAD

**Issue by jukkae** [snaekobbi/pipeline-mod-celia#30]
The current implementation of adding empty pages to the end of the volumes does not take into account the actual maximum-number-of-sheets. Thus, the volume length can exceed the intended maximum. However, this can be worked around, which makes the issue less important.

**Comment by bertfrees** [comment]
What about a regular expression to check whether the value for "maximum-number-of-sheets" is dividable by 2?

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-webui/issues/77

**Comment by jukkae** [comment]
Doesn't actually seem to occur in reality.
