### ISSUE TITLE
Make all options work

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-celia#5]
- Options that have been implemented in the generic dtbook-to-pef should not be overwritten.
- Options that were not generic enough to implement in the generic dtbook-to-pef should be implemented here.

I have fixed `$page-width` and `$page-height` in https://github.com/snaekobbi/pipeline-mod-celia/commit/54cfd05a2eabaa76e034a893efbc138b5d593072. But there are other options left. Ideally all options, especially the ones implemented here, should be covered by unit tests.

**Comment by bertfrees** [comment]
@jukkae:
- The script has the option `hyphenation` but the CSS contains the rule

``` css
book {
   hyphens: auto;
}
```
- The script has the option `include-production-notes` but the CSS contains the rule

``` css
prodnote {
   display: block;
}
```
- The option `include-note-references` is not implemented.

**Comment by jukkae** [comment]
- [x] Hyphenation
- [x] include-production-notes
- [x] include-note-references

**Comment by jukkae** [comment]
Test status for options (just to make sure I don't miss anything):
- [x] include-brf
- [x] include-preview
- [x] pef-output-dir
- [x] brf-output-dir
- [x] preview-output-dir
- [x] temp-dir
- [x] stylesheet
- [x] page-width
- [x] page-height
- [x] duplex
- [ ] minimum-number-of-sheets
- [x] maximum-number-of-sheets
- [x] include-image-groups
- [x] include-images
- [x] include-captions
- [x] include-production-notes
- [x] process-noterefs
- [x] show-braille-page-numbers
- [x] show-print-page-numbers
- [x] line-spacing
- [x] letter-spacing
- [x] hyphenation
- [x] insert-titlepage
- [x] preprocess-tables
- [x] pad-volume-endings
- [x] make-volumes-divisible-by-four
- [x] skip-typography
- [x] toc-depth

**Comment by jukkae** [comment]
- minimum-number-of-sheets is not implemented

**Comment by bertfrees** [comment]
You might want to drop `transform` from your script. At least, that was the idea. Or does the transformer need to be configurable?

**Comment by jukkae** [comment]
No, I don't think it needs to be configurable.
