### ISSUE TITLE
Fix line break before target-counter in TOC

### ISSUE THREAD

**Issue by jukkae** [snaekobbi/pipeline-mod-celia#6]
When TOC is created, there is an extra line break before the page counter.

See the [CSS](https://github.com/snaekobbi/pipeline-mod-celia/blob/celia-script/src/main/resources/css/celia-default.scss#L67) and the [expected output](https://github.com/snaekobbi/pipeline-mod-celia/blob/celia-script/src/test/xprocspec/test_script.xprocspec#L276).

Curiously, if the second empty space in content in CSS is removed (ie., `content: ' ' leader('⠐') target-counter(attr(href), page);`, the counter stays on the same line, like it is supposed to.

**Comment by bertfrees** [comment]
This is a known issue (https://github.com/braillespecs/obfl/issues/31) and has just been fixed. I will upload the latest version of mod-braille, so you can run your test again.

**Comment by bertfrees** [comment]
OK uploaded.
